# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DragAndDropQuiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draganddrop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='draganddrop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
