# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FillInTheBlankQuestion',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('question_start', models.CharField(max_length=50)),
                ('question_end', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
    ]
