# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 22:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fillintheblank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fillintheblankquestion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fillintheblankquestion',
            name='key',
        ),
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='key',
        ),
        migrations.AddField(
            model_name='fillintheblankquestion',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fillintheblankquestion',
            name='questionID',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='fillintheblankquestion',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='questionID',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
    ]
