# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillintheblank', '0002_auto_20170327_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillintheblankquestion',
            name='score',
            field=models.CharField(default='', max_length=100),
        ),
    ]
