# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillintheblank', '0002_auto_20170323_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillintheblankquestion',
            name='questionID',
            field=models.AutoField(default='DEFAULT VALUE', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionID',
            field=models.AutoField(default='DEFAULT VALUE', primary_key=True, serialize=False),
        ),
    ]
