# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fillintheblank', '0003_fillintheblankquestion_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='fillintheblankquestion',
            name='score',
        ),
        migrations.AddField(
            model_name='answer',
            name='questionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionID_text', to='fillintheblank.FillInTheBlankQuestion'),
        ),
    ]
