# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillintheblank', '0003_auto_20170306_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterModelTable(
            name='question',
            table='FillInTheBlank',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
