# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fillintheblank', '0004_auto_20170329_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fillintheblankquestion',
            name='answer',
        ),
    ]
