# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillintheblank', '0004_auto_20170322_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='key',
            field=models.IntegerField(default=0),
        ),
    ]
