# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-02 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillintheblank', '0005_auto_20170402_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_end',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_start',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
