# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fillintheblank', '0006_auto_20170402_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='title',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fillintheblank.Question'),
            preserve_default=False,
        ),
    ]
