# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fillintheblank', '0006_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillInTheBlankQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_start', models.CharField(default='', max_length=50)),
                ('question_end', models.CharField(default='', max_length=50)),
                ('answer', models.CharField(default='', max_length=50)),
                ('key', models.IntegerField(default=0)),
            ],
        ),
    ]
