# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 03:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coursemanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceQuiz',
            fields=[
                ('quizID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=140)),
                ('numberOfChoices', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='4', max_length=1)),
                ('choiceOne', models.CharField(max_length=15)),
                ('choiceTwo', models.CharField(max_length=15)),
                ('choiceThree', models.CharField(blank=True, max_length=15, null=True)),
                ('choiceFour', models.CharField(blank=True, max_length=15, null=True)),
                ('choiceFive', models.CharField(blank=True, max_length=15, null=True)),
                ('choiceSix', models.CharField(blank=True, max_length=15, null=True)),
                ('correctAnswer', models.CharField(choices=[('A', '1'), ('B', '2'), ('C', '3'), ('D', '4'), ('E', '5'), ('F', '6')], default='A', max_length=1)),
                ('difficulty', models.CharField(choices=[('Beginner', '1'), ('Intermediate', '2'), ('Advanced', '3')], default='Beginner', max_length=15)),
                ('LessonID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Lesson')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuizResponse',
            fields=[
                ('responseID', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.BooleanField(default=False)),
                ('quizID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.MultipleChoiceQuiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
