# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 23:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coursemanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('youtube', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=15)),
                ('tabs', models.CharField(choices=[('ONE', '1'), ('TWO', '2'), ('THREE', '3'), ('FOUR', '4'), ('FIVE', '5'), ('SIX', '6')], default='1', max_length=5)),
                ('tab1desc', models.TextField(default='Tab 1 Description', max_length=2000)),
                ('tab2desc', models.TextField(default='Tab 2 Description', max_length=2000)),
                ('tab3desc', models.TextField(default='Tab 3 Description', max_length=2000)),
                ('tab4desc', models.TextField(default='Tab 4 Description', max_length=2000)),
                ('tab5desc', models.TextField(default='Tab 5 Description', max_length=2000)),
                ('tab6desc', models.TextField(default='Tab 6 Description', max_length=2000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
