# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0002_shortanswerquiz_shortanswerquizresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='multiplechoicequiz',
            name='title',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='shortanswerquiz',
            name='title',
            field=models.CharField(max_length=55),
        ),
    ]
