# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0003_auto_20170212_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lesson',
        ),
        migrations.AddField(
            model_name='course',
            name='lesson',
            field=models.ManyToManyField(to='coursemanagement.Lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lessonID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
