# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 04:34
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coursemanagement', '0003_auto_20170426_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='DragAndDropQuiz',
            fields=[
                ('quizID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('difficulty', models.IntegerField(choices=[('Beginner', '1'), ('Intermediate', '2'), ('Advanced', '3')], default=2)),
                ('wordCount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('wordOne', models.CharField(max_length=15)),
                ('wordTwo', models.CharField(max_length=15)),
                ('wordThree', models.CharField(max_length=15)),
                ('wordFour', models.CharField(blank=True, max_length=15, null=True)),
                ('wordFive', models.CharField(blank=True, max_length=15, null=True)),
                ('wordSix', models.CharField(blank=True, max_length=15, null=True)),
                ('wordSeven', models.CharField(blank=True, max_length=15, null=True)),
                ('wordEight', models.CharField(blank=True, max_length=15, null=True)),
                ('wordNine', models.CharField(blank=True, max_length=15, null=True)),
                ('wordTen', models.CharField(blank=True, max_length=15, null=True)),
                ('wordEleven', models.CharField(blank=True, max_length=15, null=True)),
                ('wordTwelve', models.CharField(blank=True, max_length=15, null=True)),
                ('wordThirteen', models.CharField(blank=True, max_length=15, null=True)),
                ('wordFourteen', models.CharField(blank=True, max_length=15, null=True)),
                ('wordFifteen', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='courselessonquiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='courselessonquiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequizresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequizresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='shortanswerquiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shortanswerquiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='shortanswerquizresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shortanswerquizresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='draganddropquiz',
            name='LessonID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Lesson'),
        ),
        migrations.AddField(
            model_name='draganddropquiz',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
