# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0004_auto_20170212_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='next',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_lesson', to='coursemanagement.Lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lesson',
            name='prev',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_lesson', to='coursemanagement.Lesson'),
        ),
    ]
