# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0004_auto_20170402_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
