# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0005_auto_20170212_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='assignedCourse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_course', to='coursemanagement.Course'),
        ),
    ]
