# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0006_multiplechoicequiz_multiplechoicequizresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequiz',
            name='LessonID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Lesson'),
        ),
    ]
