# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0007_auto_20170213_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='next',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='prev',
        ),
    ]
