# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0008_auto_20170213_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='tab1',
            field=models.CharField(default='1', max_length=15),
        ),
        migrations.AddField(
            model_name='lesson',
            name='tab2',
            field=models.CharField(default='2', max_length=15),
        ),
        migrations.AddField(
            model_name='lesson',
            name='tab3',
            field=models.CharField(default='3', max_length=15),
        ),
        migrations.AddField(
            model_name='lesson',
            name='tab4',
            field=models.CharField(default='4', max_length=15),
        ),
        migrations.AddField(
            model_name='lesson',
            name='tab5',
            field=models.CharField(default='5', max_length=15),
        ),
        migrations.AddField(
            model_name='lesson',
            name='tab6',
            field=models.CharField(default='6', max_length=15),
        ),
    ]
