# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0009_auto_20170226_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lesson',
            field=models.ManyToManyField(to='coursemanagement.Lesson'),
        ),
    ]
