# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0010_auto_20170314_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='tags',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
