# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0015_auto_20170328_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLessonQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LessonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quizID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=140)),
                ('wordOne', models.CharField(max_length=15)),
                ('wordTwo', models.CharField(max_length=15)),
                ('wordThree', models.CharField(max_length=15)),
                ('wordFour', models.CharField(max_length=15)),
                ('wordFive', models.CharField(max_length=15)),
                ('LessonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Lesson')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='lesson',
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', '1'), ('Intermediate', '2'), ('Advanced', '3')], default='Beginner', max_length=15),
        ),
        migrations.AddField(
            model_name='courselessonquiz',
            name='QuizID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Quiz'),
        ),
        migrations.AddField(
            model_name='courselessonquiz',
            name='courseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Course'),
        ),
    ]
