# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0016_auto_20170329_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselessonquiz',
            name='LessonID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Lesson'),
        ),
        migrations.AlterField(
            model_name='courselessonquiz',
            name='QuizID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Quiz'),
        ),
    ]
