# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 04:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0018_auto_20170329_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courselessonquiz',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='courselessonquiz',
            name='position',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(30)]),
            preserve_default=False,
        ),
    ]
