# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0019_auto_20170329_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.CharField(default=123, max_length=15),
            preserve_default=False,
        ),
    ]
