# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('question_name', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=1000)),
            ],
        ),
    ]
