# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-31 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answerID', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=1000)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=100)),
                ('correctAnswer', models.CharField(max_length=1000)),
                ('difficulty', models.CharField(choices=[('Beginner', '1'), ('Intermediate', '2'), ('Advanced', '3')], default='Beginner', max_length=15)),
            ],
        ),
    ]
