# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-01 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortAnswer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Advanced')], default='Beginner', max_length=15),
        ),
    ]
