# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShortAnswer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_name',
            new_name='question',
        ),
    ]
