# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-02 18:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ShortAnswer', '0002_auto_20170401_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='answer',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shortAnswer_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
