# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortAnswer', '0002_auto_20170324_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correctAnswer',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
