# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortAnswer', '0003_auto_20170326_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.CharField(default='', max_length=100),
        ),
    ]
