# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShortAnswer', '0004_question_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_text', to='ShortAnswer.Question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_text', to='ShortAnswer.Question')),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questioID_text', to='ShortAnswer.Question')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_text', to='ShortAnswer.Question')),
            ],
        ),
    ]
