# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShortAnswer', '0005_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='score',
        ),
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='questionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionID_text', to='ShortAnswer.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
