# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortAnswer', '0007_remove_question_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='questionID',
            new_name='original_questionID',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
