# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShortAnswer', '0008_auto_20170330_0519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='author',
            new_name='author_question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='content_question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='title_question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='user_answer',
        ),
    ]
