# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortAnswer', '0010_auto_20170330_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.CharField(default='', max_length=100),
        ),
    ]
