# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortAnswer', '0011_auto_20170330_0621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='title',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='original_questionID',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AddField(
            model_name='answer',
            name='AnswerID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
