# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortAnswer', '0012_auto_20170330_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='AnswerID',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
