# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortAnswer', '0014_auto_20170330_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
    ]
