# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShortAnswer', '0016_auto_20170330_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
    ]
