# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShortAnswer', '0017_remove_question_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
    ]
