# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShortAnswer', '0018_remove_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
