# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tab1',
            field=models.CharField(default=b'Tab 1', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='tab1desc',
            field=models.CharField(default=b'Tab 1 Description', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='tab2',
            field=models.CharField(default=b'Tab 2', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='tab2desc',
            field=models.CharField(default=b'Tab 2 Description', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='tab3',
            field=models.CharField(default=b'Tab 3', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='tab3desc',
            field=models.CharField(default=b'Tab 3 Description', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='tab4',
            field=models.CharField(default=b'Tab 4', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='tab4desc',
            field=models.CharField(default=b'Tab 4 Description', max_length=100),
        ),
    ]
