# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video_page', '0002_auto_20170201_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tab1desc',
            field=models.TextField(default=b'Tab 1 Description', max_length=2000),
        ),
        migrations.AlterField(
            model_name='video',
            name='tab2desc',
            field=models.TextField(default=b'Tab 2 Description', max_length=2000),
        ),
        migrations.AlterField(
            model_name='video',
            name='tab3desc',
            field=models.TextField(default=b'Tab 3 Description', max_length=2000),
        ),
        migrations.AlterField(
            model_name='video',
            name='tab4desc',
            field=models.TextField(default=b'Tab 4 Description', max_length=2000),
        ),
    ]
