# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video_page', '0003_auto_20170201_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='video',
            name='tab1',
            field=models.CharField(default=b'Tab 1', max_length=15),
        ),
        migrations.AlterField(
            model_name='video',
            name='tab2',
            field=models.CharField(default=b'Tab 2', max_length=15),
        ),
        migrations.AlterField(
            model_name='video',
            name='tab3',
            field=models.CharField(default=b'Tab 3', max_length=15),
        ),
        migrations.AlterField(
            model_name='video',
            name='tab4',
            field=models.CharField(default=b'Tab 4', max_length=15),
        ),
    ]
