# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('AnswerID', models.AutoField(primary_key=True, serialize=False)),
                ('answer_one', models.CharField(blank=True, max_length=140)),
                ('answer_two', models.CharField(blank=True, max_length=140)),
                ('answer_three', models.CharField(blank=True, max_length=140)),
                ('answer_four', models.CharField(blank=True, max_length=140)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('quizID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=140)),
                ('options', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4')], default='4', max_length=2)),
                ('left_one', models.CharField(blank=True, max_length=140)),
                ('left_two', models.CharField(blank=True, max_length=140)),
                ('left_three', models.CharField(blank=True, max_length=140)),
                ('left_four', models.CharField(blank=True, max_length=140)),
                ('right_one', models.CharField(blank=True, max_length=140)),
                ('right_two', models.CharField(blank=True, max_length=140)),
                ('right_three', models.CharField(blank=True, max_length=140)),
                ('right_four', models.CharField(blank=True, max_length=140)),
            ],
        ),
    ]
