# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 05:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='AnswerID',
            new_name='resultsID',
        ),
        migrations.RemoveField(
            model_name='matching',
            name='options',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_eight',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_eleven',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_fifteen',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_five',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_fourteen',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_nine',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_seven',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_six',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_ten',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_thirteen',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_twelve',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='left_eight',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='left_eleven',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='left_fifteen',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='left_five',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='left_four',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='left_fourteen',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='left_nine',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='left_one',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='left_seven',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='left_six',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='left_ten',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='left_thirteen',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='left_three',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='left_twelve',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='left_two',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='quizID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='title',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matching',
            name='answer_options',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], default='2', max_length=2),
        ),
        migrations.AddField(
            model_name='matching',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matching',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Advanced')], default='1', max_length=12),
        ),
        migrations.AddField(
            model_name='matching',
            name='left_eight',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='matching',
            name='left_eleven',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='matching',
            name='left_fifteen',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='matching',
            name='left_five',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='matching',
            name='left_fourteen',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='matching',
            name='left_nine',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='matching',
            name='left_seven',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='matching',
            name='left_six',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='matching',
            name='left_ten',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='matching',
            name='left_thirteen',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='matching',
            name='left_twelve',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='matching',
            name='question_options',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], default='2', max_length=2),
        ),
        migrations.AddField(
            model_name='matching',
            name='right_eight',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='matching',
            name='right_eleven',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='matching',
            name='right_fifteen',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='matching',
            name='right_five',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='matching',
            name='right_fourteen',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='matching',
            name='right_nine',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='matching',
            name='right_seven',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='matching',
            name='right_six',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='matching',
            name='right_ten',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='matching',
            name='right_thirteen',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='matching',
            name='right_twelve',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='matching',
            name='string',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matching',
            name='left_one',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='matching',
            name='left_two',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='matching',
            name='right_one',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='matching',
            name='right_two',
            field=models.CharField(max_length=140),
        ),
    ]
