# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='MatchingQuestion',
            new_name='Question',
        ),
        migrations.DeleteModel(
            name='MatchingNumber',
        ),
    ]
