# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_auto_20170306_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='correct',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='number',
            name='quiz_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='rand_letter',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AlterModelTable(
            name='number',
            table='matching',
        ),
    ]
