# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_auto_20170306_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='quiz_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterModelTable(
            name='number',
            table='matching',
        ),
    ]
