# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_auto_20170323_2152'),
        ('matching', '0003_auto_20170323_1426'),
    ]

    operations = [
    ]
