# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 00:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matching', '0003_auto_20170323_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('quizID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=140)),
                ('left_one', models.CharField(blank=True, max_length=20)),
                ('left_two', models.CharField(blank=True, max_length=20)),
                ('left_three', models.CharField(blank=True, max_length=20)),
                ('left_four', models.CharField(blank=True, max_length=20)),
                ('right_one', models.CharField(blank=True, max_length=20)),
                ('right_two', models.CharField(blank=True, max_length=20)),
                ('right_three', models.CharField(blank=True, max_length=20)),
                ('right_four', models.CharField(blank=True, max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
