# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_matching'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matching',
            name='author',
        ),
    ]
