# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-27 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_merge_20170326_1954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Number',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
