# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_merge_20170326_1954'),
        ('matching', '0004_merge_20170323_2154'),
    ]

    operations = [
    ]
