# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_auto_20170327_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='options',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4')], default='4', max_length=10),
        ),
    ]
