# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0008_matching_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('AnswerID', models.AutoField(primary_key=True, serialize=False)),
                ('answer_one', models.CharField(blank=True, max_length=140)),
                ('answer_two', models.CharField(blank=True, max_length=140)),
                ('answer_three', models.CharField(blank=True, max_length=140)),
                ('answer_four', models.CharField(blank=True, max_length=140)),
            ],
        ),
        migrations.AlterField(
            model_name='matching',
            name='left_four',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='matching',
            name='left_one',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='matching',
            name='left_three',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='matching',
            name='left_two',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='matching',
            name='options',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4')], default='4', max_length=2),
        ),
        migrations.AlterField(
            model_name='matching',
            name='right_four',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='matching',
            name='right_one',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='matching',
            name='right_three',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='matching',
            name='right_two',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='answer',
            name='QuizID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.Matching'),
        ),
    ]
