# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0009_auto_20170328_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='QuizID',
        ),
    ]
