# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0013_auto_20170328_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='match',
            field=models.ForeignKey(default='Hello', on_delete=django.db.models.deletion.CASCADE, to='matching.Matching'),
        ),
        migrations.AlterField(
            model_name='matching',
            name='on',
            field=models.ForeignKey(blank=True, default='Hello', on_delete=django.db.models.deletion.CASCADE, to='matching.Answer'),
        ),
    ]
