# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0014_auto_20170328_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='match',
        ),
        migrations.RemoveField(
            model_name='matching',
            name='on',
        ),
        migrations.AddField(
            model_name='answer',
            name='matching',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='matching.Matching'),
        ),
    ]
