# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 00:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('prefID', models.AutoField(primary_key=True, serialize=False)),
                ('defaultLanguage', models.CharField(choices=[('English', '1'), ('Spanish', '2')], default='1', max_length=10)),
                ('difficulty', models.CharField(choices=[('Beginner', '1'), ('Intermediate', '2'), ('Advanced', '3')], default='1', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
