# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0010_auto_20170314_2315'),
        ('UserSettingsPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='lastVid',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Lesson'),
            preserve_default=False,
        ),
    ]
