# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserSettingsPage', '0002_preference_lastvid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='lastVid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.Lesson'),
        ),
    ]
