# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 21:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='The title of this lesson.', max_length=140, verbose_name='Lesson Title')),
                ('content', models.TextField(help_text='The instructional content of this lesson.', verbose_name='Lesson Content')),
            ],
            options={
                'ordering': ('-date_created', '-date_modified'),
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='LessonQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_in_quiz', models.PositiveIntegerField(verbose_name='Order in Quiz')),
                ('question', models.CharField(help_text="A question that can be answered with either 'Yes' or 'No'.", max_length=200, verbose_name='Question')),
                ('correct_answer', models.BooleanField(choices=[(True, b'Yes'), (False, b'No')], default=True, verbose_name='Correct Answer')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson_quiz.Lesson')),
            ],
            options={
                'ordering': ('order_in_quiz',),
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_correctly', models.BooleanField(editable=False)),
                ('question', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='lesson_quiz.LessonQuestion')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Answer',
                'verbose_name_plural': 'User Answers',
            },
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together=set([('question', 'user')]),
        ),
    ]
