# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_a', models.CharField(max_length=150)),
                ('answer_b', models.CharField(max_length=150)),
                ('answer_c', models.CharField(max_length=150)),
                ('answer_d', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'MultipleChoiceQuiz',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'MultipleChoiceQuiz',
            },
        ),
    ]
