# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-26 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quizID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=1500)),
                ('answerA', models.CharField(default='', max_length=150)),
                ('answerB', models.CharField(default='', max_length=150)),
                ('answerC', models.CharField(default='', max_length=150)),
                ('answerD', models.CharField(default='', max_length=150)),
                ('correctAnswer', models.CharField(default='', max_length=150)),
                ('score', models.CharField(default='', max_length=150)),
            ],
            options={
                'db_table': 'multipleChoice',
            },
        ),
    ]
