# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-29 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multipleChoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='score',
            field=models.CharField(default='', max_length=150),
        ),
    ]
