# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-25 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multipleChoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='question',
            new_name='q',
        ),
    ]
