# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multipleChoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answers',
            table=None,
        ),
        migrations.AlterModelTable(
            name='questions',
            table=None,
        ),
    ]
