# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multipleChoice', '0002_quiz_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='quizID',
            new_name='responseID',
        ),
    ]
