# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multipleChoice', '0002_auto_20170322_1358'),
        ('multipleChoice', '0002_auto_20170322_2200'),
    ]

    operations = [
    ]
