# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-25 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multipleChoice', '0002_auto_20170325_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='q',
            new_name='question',
        ),
    ]
