# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multipleChoice', '0002_auto_20170322_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='', max_length=150),
        ),
    ]
