# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multipleChoice', '0002_auto_20170306_2329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
        migrations.AlterModelTable(
            name='answer',
            table='multipleChoice',
        ),
        migrations.AlterModelTable(
            name='question',
            table='multipleChoice',
        ),
    ]
