# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multipleChoice', '0003_auto_20170306_2332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_a',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_b',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_c',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_d',
            field=models.CharField(default='', max_length=150),
        ),
    ]
