# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multipleChoice', '0003_auto_20170330_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='title',
        ),
        migrations.AlterField(
            model_name='response',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
