# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-25 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multipleChoice', '0004_auto_20170325_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResults',
            fields=[
                ('quizID', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.CharField(default='', max_length=150)),
            ],
            options={
                'db_table': 'multipleChoice',
            },
        ),
    ]
