# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multipleChoice', '0004_auto_20170306_2339'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
    ]
