# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-25 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multipleChoice', '0005_userresults'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quiz',
            table=None,
        ),
    ]
