# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multipleChoice', '0005_auto_20170306_2340'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='multipleChoice',
        ),
    ]
