# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-25 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multipleChoice', '0007_auto_20170325_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresults',
            name='title',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
