# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-25 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multipleChoice', '0008_userresults_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserResults',
        ),
        migrations.AlterModelTable(
            name='quiz',
            table='multipleChoice',
        ),
    ]
